services:
  - type: web
    name: ml-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python load_model.py
    repo: https://github.com/Parthsawant1298/ml-project-1743091323.git
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: MODEL_FILE
        value: best_model.pkl
